# Imports

In [1]:
import numpy as np
from time import time

# Load input

In [134]:
INPUT_FILE = 'test.txt'
#INPUT_FILE = 'input.txt'

In [135]:
input_list = np.genfromtxt(INPUT_FILE, delimiter=' -> ', dtype='str')
mapper = np.vectorize(lambda x: (int(x.split(',')[0]), int(x.split(',')[1])))
line_starts = np.vstack(mapper(input_list[:, 0])).T
line_ends = np.vstack(mapper(input_list[:, 1])).T

# Part 1

In [136]:
start_t = time()
grid_size = max(line_starts.max(), line_ends.max()) + 1
grid = np.zeros((grid_size, grid_size), dtype='uint64')

lines = np.concatenate([line_starts, line_ends], axis=1)

hor_filtered_lines = lines[lines[:, 1] == lines[:, 3]]
ver_filtered_lines = lines[lines[:, 0] == lines[:, 2]]

for line in hor_filtered_lines:
    line_start = min(line[0], line[2])
    line_end = max(line[0], line[2]) + 1
    grid[line[1], line_start:line_end] += 1

for line in ver_filtered_lines:
    line_start = min(line[1], line[3])
    line_end = max(line[1], line[3]) + 1
    grid[line_start:line_end, line[0]] += 1 
    
solution = np.sum(grid >= 2)
end_t = time()
print(f'SOLUTION: {solution}, TIME: {round((end_t - start_t) * 1000, 4)}ms')

SOLUTION: 5, TIME: 1.097ms


# Part 2

In [141]:
start_t = time()
grid_size = max(line_starts.max(), line_ends.max()) + 1
grid = np.zeros((grid_size, grid_size), dtype='uint64')

lines = np.concatenate([line_starts, line_ends], axis=1)

hor_filter = lines[:, 1] == lines[:, 3]
ver_filter = lines[:, 0] == lines[:, 2]
diag_filter = ~(hor_filter | ver_filter)

hor_filtered_lines = lines[hor_filter]
ver_filtered_lines = lines[ver_filter]
right_diagonal_filtered_lines = lines[diag_filter 
                                      & (((lines[:, 1] < lines[:, 3]) & (lines[:, 0] < lines[:, 2])) | ((lines[:, 3] < lines[:, 1]) & (lines[:, 2] < lines[:, 0])))]
left_diagonal_filtered_lines = lines[diag_filter 
                                     & (((lines[:, 1] < lines[:, 3]) & (lines[:, 0] > lines[:, 2])) | ((lines[:, 3] < lines[:, 1]) & (lines[:, 2] > lines[:, 0])))]

for line in hor_filtered_lines:
    line_start = min(line[0], line[2])
    line_end = max(line[0], line[2]) + 1
    grid[line[1], line_start:line_end] += 1

for line in ver_filtered_lines:
    line_start = min(line[1], line[3])
    line_end = max(line[1], line[3]) + 1
    grid[line_start:line_end, line[0]] += 1
    
for line in right_diagonal_filtered_lines:
    line_start_ver = min(line[1], line[3])
    line_end_ver = max(line[1], line[3])
    line_start_hor = min(line[0], line[2])
    line_end_hor = max(line[0], line[2])
    line_length = line_end_ver - line_start_ver + 1
    for i in range(line_length):
        grid[line_start_hor + i, line_start_ver + i] += 1
        
for line in left_diagonal_filtered_lines:
    line_start_ver = min(line[1], line[3])
    line_end_ver = max(line[1], line[3])
    line_start_hor = max(line[0], line[2])
    line_end_hor = min(line[0], line[2])
    line_length = line_end_ver - line_start_ver
    for i in range(line_length):
        grid[line_start_hor - i, line_start_ver + i] += 1
    
solution = np.sum(grid >= 2)
end_t = time()
print(f'SOLUTION: {solution}, TIME: {round((end_t - start_t) * 1000, 4)}ms')

SOLUTION: 11, TIME: 1.3201ms


In [142]:
right_diagonal_filtered_lines, left_diagonal_filtered_lines

(array([[6, 4, 2, 0],
        [0, 0, 8, 8]]),
 array([[8, 0, 0, 8],
        [5, 5, 8, 2]]))

In [143]:
grid

array([[1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 2, 0, 0],
       [1, 0, 2, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 1, 2, 2, 3, 1, 1, 2, 1, 1],
       [0, 0, 0, 2, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 2, 0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [2, 2, 2, 1, 1, 1, 0, 0, 0, 0]], dtype=uint64)

In [ ]:
#1010000110
#0111000200
#0020101110
#0001020200
#0112313211
#0001020000
#0010001000
#0100000100
#1000000010
#2221110000